#######################################################################
# WARNING: This file automatically generated by Borg on <%=Date.create().format('{yyyy}-{MM}-{dd} {HH}:{mm}:{ss} {tz}')%>
#          If you need to edit this file, do so in the Borg repository.
#          Any change you make here WILL be overridden on assimilation.
#######################################################################

<% for own key, value of @server.openssh.server: %>
<%  if Array.isArray value: %>
<%    for item in value: %>
<%=     "#{key} #{item}" %>
<%    end %>
<%  else: %>
<%=   "#{key} #{value}"%>
<%  end %>
<% end %>
